gadgetSuccess:
  javascripts:
    - %OP_JQUERY_URL%

gadgetPlotSuccess:
  layout: plain
  stylesheets: [-backend, gadgetPlot]
  javascripts: [%OP_JQUERY_URL%, %OP_JQUERYUI_URL%]

addGadgetSuccess:
  layout: plain
  stylesheets: [-backend]
  javascripts: [%OP_JQUERY_URL%]

editGadgetSuccess:
  layout: plain
  stylesheets: [-backend]
  javascripts: [%OP_JQUERY_URL%]
